---
- hosts: all
  become: yes
  tasks:
    - name: updating cache and dist-upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: cleaning & removeing
      apt:
        update_cache: no
        autoremove: yes
        autoclean: yes
