# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kali-linux-dev"
  # for provisioning I would always recommend
  # a script, because then you can leave
  # documentation
  config.vm.provision "shell", path: "prov.sh"
end
